### ISSUE TITLE
1.13 Support?

### ISSUE THREAD

**Issue by redbrain** [Skyost/AdSky#2]
**Is your feature request related to a problem ? Please describe.**
I tried to install AdSky on a 1.13.1 Spigot server and got an error message

**Describe the solution you'd like :**
I would like an update for 1.13 support.

**Describe alternatives you've considered :**
I don't have any alternatives to AdSky...

**Additional context :**
If you want errror messages, let me know.

**Comment by Skyost** [comment]
What is the error message ?

**Comment by redbrain** [comment]
```
[21:40:56] [Server thread/INFO]: [AdSky] Enabling AdSky v0.1
[21:40:56] [Server thread/INFO]: [0;33;22m[AdSky] Loading config...[m
[21:40:56] [Server thread/INFO]: [0;32;22m[AdSky] Config loaded with success ![m
[21:40:56] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:40:56] [Thread-9/INFO]: [0;33;22m[AdSky] Deleting expired ads...[m
[21:40:56] [Server thread/INFO]: Done (11.752s)! For help, type "help"
[21:40:57] [Thread-9/INFO]: [0;31;22m[AdSky] Unable to delete expired ads :[m
[21:40:57] [Thread-9/INFO]: [0;31;22m[AdSky] java.io.IOException: Invalid response code : 301.
	at fr.skyost.adsky.core.tasks.BackgroundTask.httpPost(BackgroundTask.java:198)
	at fr.skyost.adsky.core.tasks.BackgroundTask.deleteExpiredAds(BackgroundTask.java:127)
	at fr.skyost.adsky.core.tasks.BackgroundTask.run(BackgroundTask.java:81)
	at java.lang.Thread.run(Unknown Source)
[m
[21:40:57] [Thread-9/INFO]: [0;33;22m[AdSky] Getting ads...[m
[21:40:57] [Thread-9/INFO]: [0;31;22m[AdSky] Unable to request ads :[m
[21:40:57] [Thread-9/INFO]: [0;31;22m[AdSky] java.io.IOException: Invalid response code : 301.
	at fr.skyost.adsky.core.tasks.BackgroundTask.httpPost(BackgroundTask.java:198)
	at fr.skyost.adsky.core.tasks.BackgroundTask.requestAds(BackgroundTask.java:147)
	at fr.skyost.adsky.core.tasks.BackgroundTask.run(BackgroundTask.java:86)
	at java.lang.Thread.run(Unknown Source)
[m
[21:40:57] [Thread-9/INFO]: [0;32;22m[AdSky] Scheduled next ad broadcast (if available) on Sat Sep 22 00:00:01 EDT 2018.[m
```

**Comment by Skyost** [comment]
It's not Minecraft 1.13 : "Invalid response code : 301". Is your server up and running ?

**Comment by redbrain** [comment]
No, this was a test of the plugin. So if I forwarded it and had players join, this error message would disappear?
> Oh, and by the way, thanks for all of your help so far.

**Comment by Skyost** [comment]
No problem :wink:

I was talking about the [AdSky server](https://github.com/Skyost/AdSky#installation) ([screenshot](https://i.imgur.com/VWIGNmO.png)).

**Comment by redbrain1014** [comment]
Oh, my bad. Thanks for the support. I plan to launch my server's website soon. Tell me if your interested in my server! :shipit:

**Comment by redbrain** [comment]
Oh, my bad. Thanks for the support. I plan to launch my server's website soon. Can I do this on a github.io page??

**Comment by redbrain** [comment]
Oops, sorry for accidentally closing the issue. Re-posting my last comment:

> **redbrain1014 said** Oh, my bad. Thanks for the support. I plan to launch my server's website soon. Can I do this on a github.io page??

**Comment by Skyost** [comment]
No problem. You can't do it on Github Pages as you need a PHP / MySQL server. Btw, do not hesitate to download the [Server Tarball](https://github.com/Skyost/AdSky/archive/server.zip) (instead of the released ZIP file), which fixes some bugs.

**Comment by redbrain** [comment]
I may be getting something wrong, but you can pretty much code your own HTML on GitHub. (Right?)
So if I were to add files for a plugin like PHP Design Objects and then [use it in this manner](https://www.w3schools.com/Php/php_mysql_connect.asp), could I then use a GitHub Page to host that?
Yeah, things are never simple. I'm probably missing something :octocat:

**Comment by Skyost** [comment]
Yes, you're probably missing the concept of PHP : PHP is not HTML.    
HTML are basically static files served over the network. PHP files must be interpreted using a server before being server over the network (and currently, Github Pages does not provide that server).

**Comment by redbrain** [comment]
Looks like I'm getting a PHP/MySql domain soon!
> Sorry for the trouble.

**Comment by Skyost** [comment]
No problem :wink:

**Comment by redbrain** [comment]
I'm trying to be cost-effective, so can I host on a server that you own (if you own one) ?
Eg:`adsky.com/servername/adsky/etc`?

**Comment by Skyost** [comment]
I'm not hosting a server, AdSky is a self-host solution, sorry. But there are some free PHP / MySQL servers around the web :wink:
